// <auto-generated>
// Code generated by LUISGen .\FlightBooking.json -cs Luis.FlightBooking -o .
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;

namespace Microsoft.BotBuilderSamples
{
    public partial class Conversation: IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent {
            discussCampus,
            discussHobbies,
            discussFeeling,
            discussCoursework,
            discussLecturer,
            discussModule,
            discussSelf,
            endConversation,
            None
        };
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {

            // Built-in entities
            public DateTimeSpec[] datetime;

            // Lists
            public string Module;
            public string Lecturer;
            public string Opinion;
            public string Feeling; 

            public string UserName;
        

            // Composites
            public class _InstanceModule
            {
                public InstanceData[] Module;
            }
        
            public class _InstanceForModule
            {
                 public string[][] Module;
                [JsonProperty("$instance")]
                public _InstanceModule _instance;
            }
        
           

            // Instance
            public class _Instance
            {
                public InstanceData[] datetime;
                public InstanceData[] Module;
                public InstanceData[] Lecturer;
                public InstanceData[] Opinion;
                public InstanceData[] Feeling;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<ConversationRecognizer>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
