// <auto-generated>
// Code generated by LUISGen Conversation.json -cs Luis.Conversation -o .
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Luis
{
    public partial class Conversation: IRecognizerConvert
    {
        [JsonProperty("text")]
        public string Text;

        [JsonProperty("alteredText")]
        public string AlteredText;

        public enum Intent {
            discussCampus, 
            discussExtracurricular, 
            discussFeeling, 
            discussLecturer, 
            discussModule, 
            endConversation, 
            greeting, 
            None
        };
        [JsonProperty("intents")]
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] Emotion;

            public string[] Extracurricular;

            public string[] Lecturer;

            public string[] Module;

            public string[] Number;

            public string[] NumberOfModules;

            public string[] Opinion;

            public string[] Place;

            public string[] Stage;

            public string[] UserName;

            // Instance
            public class _Instance
            {
                public InstanceData[] Emotion;
                public InstanceData[] Extracurricular;
                public InstanceData[] Lecturer;
                public InstanceData[] Module;
                public InstanceData[] Number;
                public InstanceData[] NumberOfModules;
                public InstanceData[] Opinion;
                public InstanceData[] Place;
                public InstanceData[] Stage;
                public InstanceData[] UserName;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        [JsonProperty("entities")]
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<Conversation>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
